@startmindmap
<style>
:depth(0) {
    BackgroundColor #FF5F46
    LineColor #FF5F46
    FontColor #ffffff
    LineThickness 3.0
}
:depth(1) {
    BackgroundColor #0078D4
    LineColor #0078D4
    LineThickness 3.0
    FontColor #FFFFFF
}
:depth(2) {
    BackgroundColor #ffb900
    LineColor #ffb900
    LineThickness 3.0
    FontColor #000000
}
boxless {
    FontColor #000000
}
</style>
+ Creating a Table:\nExplicit at Schema
++ Required grants
+++_ USE CATALOG on catalog
+++_ USE SCHEMA on schema
+++_ CREATE TABLE on schema
++ Characteristics
+++_ Limited to one schema
+++_ No unnecessary privileges
+++_ Common for controlled schemas
-- GRANT syntax
---_ GRANT CREATE TABLE ON SCHEMA ...
@endmindmap
