@startmindmap
<style>
:depth(0) {
    BackgroundColor #FF5F46
    LineColor #FF5F46
    FontColor #ffffff
    LineThickness 3.0
}
:depth(1) {
    BackgroundColor #0078D4
    LineColor #0078D4
    LineThickness 3.0
    FontColor #FFFFFF
}
:depth(2) {
    BackgroundColor #ffb900
    LineColor #ffb900
    LineThickness 3.0
    FontColor #000000
}
boxless {
    FontColor #000000
}
</style>
+ Inherited Permissions\nFrom Catalog
++ Required grants
+++_ USE CATALOG + ALL PRIVILEGES or SELECT\non catalog
++ Effect
+++_ Access to all schemas, tables, views
+++_ Includes future objects
++ Characteristics
+++_ Most permissive model
+++_ Broad access across catalog
+++_ Careful assessment needed
-- Use case
---_ Analysts needing full catalog access
@endmindmap
