@startmindmap
<style>
:depth(0) {
    BackgroundColor #FF5F46
    LineColor #FF5F46
    FontColor #ffffff
    LineThickness 3.0
}
:depth(1) {
    BackgroundColor #0078D4
    LineColor #0078D4
    LineThickness 3.0
    FontColor #FFFFFF
}
:depth(2) {
    BackgroundColor #ffb900
    LineColor #ffb900
    LineThickness 3.0
    FontColor #000000
}
boxless {
    FontColor #000000
}
</style>
+ Row and\nColumn Security
++ Column masking
+++_ Masking function per column
+++_ Returns real / redacted / transformed value
+++_ Based on group membership
++ Row filtering
+++_ Filter function per table
+++_ Returns boolean (visible/hidden row)
+++_ One function for all row rules
++ Characteristics
+++_ Centralized logic at table level
+++_ Combinatorial flexibility
+++_ Performance alignment
+++_ Fewer objects to govern
@endmindmap
