@startmindmap
<style>
:depth(0) {
    BackgroundColor #FF5F46
    LineColor #FF5F46
    FontColor #ffffff
    LineThickness 3.0
}
:depth(1) {
    BackgroundColor #0078D4
    LineColor #0078D4
    LineThickness 3.0
    FontColor #FFFFFF
}
:depth(2) {
    BackgroundColor #ffb900
    LineColor #ffb900
    LineThickness 3.0
    FontColor #000000
}
boxless {
    FontColor #000000
}
</style>
+ Row & Column Security\n(Implementation)
++ Column masking
+++_ CREATE FUNCTION phone_mask(...)
+++_ CASE WHEN is_account_group_member(...)
++++_ THEN real value ELSE 'REDACTED'
+++_ ALTER TABLE ... ALTER COLUMN ...\nSET MASK <function>
++ Row filtering
+++_ CREATE FUNCTION nation_filter(...)
+++_ IF(is_account_group_member('admin'), true,\nc_nationkey = 21)
+++_ ALTER TABLE ...\nSET ROW FILTER <function> ON (col)
++ Effect
+++_ Admins see all data
+++_ Non-admins: redacted + filtered rows
@endmindmap
