@startmindmap
<style>
:depth(0) {
    BackgroundColor #FF5F46
    LineColor #FF5F46
    FontColor #ffffff
    LineThickness 3.0
}
:depth(1) {
    BackgroundColor #0078D4
    LineColor #0078D4
    LineThickness 3.0
    FontColor #FFFFFF
}
:depth(2) {
    BackgroundColor #ffb900
    LineColor #ffb900
    LineThickness 3.0
    FontColor #000000
}
boxless {
    FontColor #000000
}
</style>
+ Secrets in\nEnvironment Variables
++ Syntax
+++_ STORAGE_KEY={{secrets/storage/account-key}}
+++_ In init scripts / env config
++ Access in init scripts
+++_ $STORAGE_KEY bash variable
++ Warning
+++_ Accessible to all cluster users
+++_ Use only when universally needed
++ Reminder
+++_ Restart cluster after secret update
+++_ Cluster caches values at start
@endmindmap
