@startmindmap
<style>
:depth(0) {
    BackgroundColor #FF5F46
    LineColor #FF5F46
    FontColor #ffffff
    LineThickness 3.0
}
:depth(1) {
    BackgroundColor #0078D4
    LineColor #0078D4
    LineThickness 3.0
    FontColor #FFFFFF
}
:depth(2) {
    BackgroundColor #ffb900
    LineColor #ffb900
    LineThickness 3.0
    FontColor #000000
}
boxless {
    FontColor #000000
}
</style>
+ Secrets in\nSpark Configurations
++ Syntax
+++_ spark.storage.key\n{{secrets/storage/account-key}}
+++_ Double curly braces
++ Configuration location
+++_ Cluster Advanced Options
+++_ Spark configuration property
++ Access in notebook
+++_ spark.conf.get("spark.storage.key")
++ Warning
+++_ All cluster users (CAN ATTACH TO)\ncan read Spark configs
+++_ Use only when all users need access
@endmindmap
