@startmindmap
<style>
:depth(0) {
    BackgroundColor #FF5F46
    LineColor #FF5F46
    FontColor #ffffff
    LineThickness 3.0
}
:depth(1) {
    BackgroundColor #0078D4
    LineColor #0078D4
    LineThickness 3.0
    FontColor #FFFFFF
}
:depth(2) {
    BackgroundColor #ffb900
    LineColor #ffb900
    LineThickness 3.0
    FontColor #000000
}
boxless {
    FontColor #000000
}
</style>
+ Secret Scopes in\nAzure Databricks
++ Purpose
+++_ Organize secrets
+++_ Control access to secrets
++ Databricks-backed scopes
+++_ Secrets in Databricks encrypted DB
+++_ Managed via CLI / API
++ Azure Key Vault-backed scopes
+++_ Read-only interface to AKV
+++_ Manage secrets in Key Vault
+++_ Enterprise security integration
+++_ Network restriction support
+++_ Auto-updated on secret rotation
-- Preferred for production
---_ Aligns with Azure security
---_ No cross-system sync needed
@endmindmap
