@startmindmap
<style>
:depth(0) {
    BackgroundColor #FF5F46
    LineColor #FF5F46
    FontColor #ffffff
    LineThickness 3.0
}
:depth(1) {
    BackgroundColor #0078D4
    LineColor #0078D4
    LineThickness 3.0
    FontColor #FFFFFF
}
:depth(2) {
    BackgroundColor #ffb900
    LineColor #ffb900
    LineThickness 3.0
    FontColor #000000
}
boxless {
    FontColor #000000
}
</style>
+ Service Principals\nfor Data Access
++ What it is
+++_ Identity for apps & services
+++_ Automated user account for apps
++ 3 Key components
+++_ Application (client) ID
+++_ Directory (tenant) ID
+++_ Client secret (password-like)
++ Advantages
+++_ No manual login needed
+++_ Consistent across environments
+++_ Precise access control
-- Note
---_ Managed identities preferred
---_ SPs useful when MI not available
@endmindmap
