@startmindmap
<style>
:depth(0) {
    BackgroundColor #FF5F46
    LineColor #FF5F46
    FontColor #ffffff
    LineThickness 3.0
}
:depth(1) {
    BackgroundColor #0078D4
    LineColor #0078D4
    LineThickness 3.0
    FontColor #FFFFFF
}
:depth(2) {
    BackgroundColor #ffb900
    LineColor #ffb900
    LineThickness 3.0
    FontColor #000000
}
boxless {
    FontColor #000000
}
</style>
+ Data Profiling\nin Unity Catalog
++ Profile Types
+++ Snapshot
++++_ Entire table metrics
++++_ General-purpose tables
+++ Time Series
++++_ Tracks metrics over time
++++_ Detects trends & drift
+++ Inference
++++_ ML model monitoring
++++_ Inputs, predictions, accuracy
++ Create via UI
+++ Catalog Explorer
++++_ Quality tab
++++_ Configure profiling
++ Create via API
+++ Databricks SDK
++++_ WorkspaceClient
++++_ quality_monitors.create()
-- Output Tables
---_ Profile metrics table
---_ Drift metrics table
@endmindmap
