@startmindmap
<style>
:depth(0) {
    BackgroundColor #FF5F46
    LineColor #FF5F46
    FontColor #ffffff
    LineThickness 3.0
}
:depth(1) {
    BackgroundColor #0078D4
    LineColor #0078D4
    LineThickness 3.0
    FontColor #FFFFFF
}
:depth(2) {
    BackgroundColor #ffb900
    LineColor #ffb900
    LineThickness 3.0
    FontColor #000000
}
boxless {
    FontColor #000000
}
</style>
+ Aggregate Data to\nCalculate Summary Statistics
++ Common Functions
+++ count()
++++_ Rows per group
+++ sum()
++++_ Total of column values
+++ avg()
++++_ Mean value
+++ min() / max()
++++_ Extremes
++ PySpark
+++ agg() method
++++_ After groupBy()
++++_ Multiple aggregations
++++_ .alias() to rename
-- SQL
--- SELECT with GROUP BY
----_ COUNT, SUM, AVG, MIN, MAX
--- HAVING clause
----_ Filters groups after aggregation
----_ E.g. SUM > 20
@endmindmap
