@startmindmap
<style>
:depth(0) {
    BackgroundColor #091f2c
    FontColor #ffffff
    LineThickness 3.0
}
:depth(1) {
    BackgroundColor #ffb900
    LineColor #ffb900
    LineThickness 3.0
    FontColor #000000
}
:depth(2) {
    BackgroundColor #f4364c
    LineColor #f4364c
    LineThickness 3.0
    FontColor #ffffff
}
boxless {
    FontColor #000000
}
</style>
+ Navigating the\nWorkspace UI
++ Sidebar
+++ Workspace objects
++++_ Notebooks, Repos, Files
+++ Recents
++++_ Recently accessed items
+++ Catalog
++++_ Unity Catalog browser
+++ Jobs & Pipelines
++++_ Orchestration tools
+++ Compute
++++_ Clusters & warehouses
+++ Marketplace
++++_ Partner integrations
-- Product Areas
--- SQL
----_ SQL Editor, Queries, Dashboards
----_ Genie, Alerts, SQL Warehouses
--- Data Engineering
----_ Job Runs, Data Ingestion
--- Machine Learning
----_ Experiments, Features, Models, Serving
-- - New
---_ Create workspace objects
---_ Create compute resources
-- Top Bar
---_ Search workspace objects
---_ Access recent items
---_ Change language preferences
@endmindmap
