@startmindmap
<style>
:depth(0) {
    BackgroundColor #FF5F46
    LineColor #FF5F46
    FontColor #ffffff
    LineThickness 3.0
}
:depth(1) {
    BackgroundColor #0078D4
    LineColor #0078D4
    LineThickness 3.0
    FontColor #FFFFFF
}
:depth(2) {
    BackgroundColor #ffb900
    LineColor #ffb900
    LineThickness 3.0
    FontColor #000000
}
boxless {
    FontColor #000000
}
</style>
* Machine Learning
** Model Lifecycle
***_ Build models at scale
***_ Train models
***_ Deploy models
** MLflow
***_ Open-source ML lifecycle mgmt
***_ Experimentation tracking
***_ Reproducibility
***_ Deployment management
** Supported Frameworks
***_ TensorFlow
***_ PyTorch
***_ Scikit-learn
@endmindmap
