@startmindmap
<style>
:depth(0) {
    BackgroundColor #FF5F46
    LineColor #FF5F46
    FontColor #ffffff
    LineThickness 3.0
}
:depth(1) {
    BackgroundColor #0078D4
    LineColor #0078D4
    LineThickness 3.0
    FontColor #FFFFFF
}
:depth(2) {
    BackgroundColor #ffb900
    LineColor #ffb900
    LineThickness 3.0
    FontColor #000000
}
boxless {
    FontColor #000000
}
</style>
* Databricks Runtime
** What it is
***_ Customized Apache Spark builds
***_ Performance improvements
***_ Additional libraries included
** Specialized Versions
***_ General data processing
***_ Machine Learning runtime
***_ Graph processing
***_ Genomics
** Version Management
***_ Multiple versions available
***_ Long-Term Support (LTS) releases
***_ Specifies Spark version & dates
** Lifecycle Stages
***_ Legacy: available, not recommended
***_ Deprecated: marked for removal
***_ End of Support: no more patches
***_ End of Life: retired, unavailable
** Maintenance Updates
***_ Apply by restarting cluster
@endmindmap
