@startmindmap
<style>
:depth(0) {
    BackgroundColor #FF5F46
    LineColor #FF5F46
    FontColor #ffffff
    LineThickness 3.0
}
:depth(1) {
    BackgroundColor #0078D4
    LineColor #0078D4
    LineThickness 3.0
    FontColor #FFFFFF
}
:depth(2) {
    BackgroundColor #ffb900
    LineColor #ffb900
    LineThickness 3.0
    FontColor #000000
}
boxless {
    FontColor #000000
}
</style>
* Databricks SQL
** What it is
***_ Data warehousing in Lakehouse
***_ Query open format data in data lake
***_ ANSI SQL support
** Tools
***_ SQL Editor
***_ Dashboards
***_ Visualization tools
***_ External BI tool integrations
** Target Users
***_ Analysts and business users
***_ No need to learn new languages
** Requirements
***_ Premium tier only
***_ Runs on SQL Warehouses
@endmindmap
