@startmindmap
<style>
:depth(0) {
    BackgroundColor #FF5F46
    LineColor #FF5F46
    FontColor #ffffff
    LineThickness 3.0
}
:depth(1) {
    BackgroundColor #0078D4
    LineColor #0078D4
    LineThickness 3.0
    FontColor #FFFFFF
}
:depth(2) {
    BackgroundColor #ffb900
    LineColor #ffb900
    LineThickness 3.0
    FontColor #000000
}
boxless {
    FontColor #000000
}
</style>
* What is\na Schema?
** Second level in namespace
***_ catalog.schema.table
** Groups related data assets
***_ Single use case or project
***_ Team workspace
** Contains
***_ Tables
***_ Views
***_ Functions
***_ Volumes
** Also called "database"
***_ CREATE DATABASE = CREATE SCHEMA
***_ Terms interchangeable in Databricks SQL
@endmindmap
