@startmindmap
<style>
:depth(0) {
    BackgroundColor #FF5F46
    LineColor #FF5F46
    FontColor #ffffff
    LineThickness 3.0
}
:depth(1) {
    BackgroundColor #0078D4
    LineColor #0078D4
    LineThickness 3.0
    FontColor #FFFFFF
}
:depth(2) {
    BackgroundColor #ffb900
    LineColor #ffb900
    LineThickness 3.0
    FontColor #000000
}
boxless {
    FontColor #000000
}
</style>
* Modify Catalog\nOwnership & Properties
** ALTER CATALOG statement
** Transfer ownership
***_ SET OWNER TO group_name
***_ Only owner/admin/MANAGE privilege
** Apply tags
***_ SET TAGS (key = 'value', ...)
***_ Searchable metadata for governance
** Enable Predictive Optimization
***_ Automates compaction & vacuum
***_ Tables inherit setting unless overridden
@endmindmap
