@startmindmap
<style>
:depth(0) {
    BackgroundColor #FF5F46
    LineColor #FF5F46
    FontColor #ffffff
    LineThickness 3.0
}
:depth(1) {
    BackgroundColor #0078D4
    LineColor #0078D4
    LineThickness 3.0
    FontColor #FFFFFF
}
:depth(2) {
    BackgroundColor #ffb900
    LineColor #ffb900
    LineThickness 3.0
    FontColor #000000
}
boxless {
    FontColor #000000
}
</style>
* Source File\nType Characteristics
** Text-Based Formats
*** CSV
****_ Human-readable
****_ Schema variability issues
****_ No compression efficiency
*** JSON
****_ Semi-structured support
****_ Text-to-type conversion overhead
** Columnar Formats
*** Parquet
****_ Better compression
****_ Column pruning
****_ Embedded schema
*** ORC
****_ Similar to Parquet
****_ Good for Hive
** Semi-Structured
***_ XML / Nested JSON
***_ Hierarchical data
***_ Requires flattening logic
@endmindmap
