@startmindmap
<style>
:depth(0) {
    BackgroundColor #FF5F46
    LineColor #FF5F46
    FontColor #ffffff
    LineThickness 3.0
}
:depth(1) {
    BackgroundColor #0078D4
    LineColor #0078D4
    LineThickness 3.0
    FontColor #FFFFFF
}
:depth(2) {
    BackgroundColor #ffb900
    LineColor #ffb900
    LineThickness 3.0
    FontColor #000000
}
boxless {
    FontColor #000000
}
</style>
* Spark Structured\nStreaming
** Streaming Sources
***_ Kafka / Azure Event Hubs
***_ Delta change data feed
***_ Cloud storage (Auto Loader)
***_ Custom sources
** Guarantees
***_ Exactly-once processing
***_ Fault tolerant checkpointing
** When to Use
***_ Fine-grained streaming control
***_ Custom watermarking / windowing
***_ Sources not in higher abstractions
** Output Modes
***_ Append
***_ Complete
***_ Update
@endmindmap
