@startmindmap
<style>
:depth(0) {
    BackgroundColor #FF5F46
    LineColor #FF5F46
    FontColor #ffffff
    LineThickness 3.0
}
:depth(1) {
    BackgroundColor #0078D4
    LineColor #0078D4
    LineThickness 3.0
    FontColor #FFFFFF
}
:depth(2) {
    BackgroundColor #ffb900
    LineColor #ffb900
    LineThickness 3.0
    FontColor #000000
}
boxless {
    FontColor #000000
}
</style>
* Photon Acceleration
** What it is
***_ Native code query engine
***_ Replaces standard Spark components
** Best for
***_ Complex joins & aggregations
***_ Large table scans
***_ Wide table transformations
***_ Disk-intensive workloads
** Minimal benefit for
***_ Simple ETL on small data
***_ Jobs completing in < 2 seconds
** Enabled by default
***_ Databricks Runtime 9.1 LTS+
***_ Configurable at cluster creation
** Not compatible with
***_ GPU-enabled clusters
@endmindmap
