@startmindmap
<style>
:depth(0) {
    BackgroundColor #FF5F46
    LineColor #FF5F46
    FontColor #ffffff
    LineThickness 3.0
}
:depth(1) {
    BackgroundColor #0078D4
    LineColor #0078D4
    LineThickness 3.0
    FontColor #FFFFFF
}
:depth(2) {
    BackgroundColor #ffb900
    LineColor #ffb900
    LineThickness 3.0
    FontColor #000000
}
boxless {
    FontColor #000000
}
</style>
* Commit & Push
** Before Committing
***_ Visual diffs in Git dialog
***_ Review list of changed files
** Commit Steps
***_ Descriptive commit message
***_ Explain what and why
***_ Select Commit & Push
** Protected Branches
***_ Cannot push directly to main
***_ Create feature branch first
***_ Use PR to merge
** Output Handling
***_ Outputs excluded for .py, .sql, .r
***_ Use IPYNB format to include outputs
@endmindmap
