@startmindmap
<style>
:depth(0) {
    BackgroundColor #FF5F46
    LineColor #FF5F46
    FontColor #ffffff
    LineThickness 3.0
}
:depth(1) {
    BackgroundColor #0078D4
    LineColor #0078D4
    LineThickness 3.0
    FontColor #FFFFFF
}
:depth(2) {
    BackgroundColor #ffb900
    LineColor #ffb900
    LineThickness 3.0
    FontColor #000000
}
boxless {
    FontColor #000000
}
</style>
* Bundle Configuration\nStructure
** databricks.yml
***_ Root of bundle project
***_ Primary configuration file
** Key Sections
***_ bundle: name
***_ resources: jobs, pipelines
***_ targets: dev, prod
***_ include: additional YAML files
** Organization
***_ Split into separate YAML files
***_ Use include mapping
***_ Manageable configurations
@endmindmap
