@startmindmap
<style>
:depth(0) {
    BackgroundColor #FF5F46
    LineColor #FF5F46
    FontColor #ffffff
    LineThickness 3.0
}
:depth(1) {
    BackgroundColor #0078D4
    LineColor #0078D4
    LineThickness 3.0
    FontColor #FFFFFF
}
:depth(2) {
    BackgroundColor #ffb900
    LineColor #ffb900
    LineThickness 3.0
    FontColor #000000
}
boxless {
    FontColor #000000
}
</style>
* Bundle Variables
** Define Variables
***_ In variables: section
***_ description & default value
** Substitution Syntax
***_ ${var.variable_name}
***_ Use anywhere in YAML config
** Setting Values
***_ Default in definition
***_ Override per target
***_ CLI: --var="name=value"
***_ Env: BUNDLE_VAR_ prefix
** Per-Environment Override
***_ dev: dev cluster_id
***_ prod: prod cluster_id
***_ Different names per env
@endmindmap
