@startmindmap
<style>
:depth(0) {
    BackgroundColor #FF5F46
    LineColor #FF5F46
    FontColor #ffffff
    LineThickness 3.0
}
:depth(1) {
    BackgroundColor #0078D4
    LineColor #0078D4
    LineThickness 3.0
    FontColor #FFFFFF
}
:depth(2) {
    BackgroundColor #ffb900
    LineColor #ffb900
    LineThickness 3.0
    FontColor #000000
}
boxless {
    FontColor #000000
}
</style>
* Impact of\nCluster Consumption
** Idle Clusters
***_ Unexpected charges
***_ Overnight / weekends
***_ Financial risk
** Under-Provisioned
***_ Jobs take longer
***_ User delays
***_ Missed deadlines
** Goal
***_ Match resources\nto workloads
***_ Balance cost\nand performance
** Benefits of Monitoring
***_ Identify waste early
***_ Spot bottlenecks
***_ Establish baselines
@endmindmap
