@startmindmap
<style>
:depth(0) {
    BackgroundColor #FF5F46
    LineColor #FF5F46
    FontColor #ffffff
    LineThickness 3.0
}
:depth(1) {
    BackgroundColor #0078D4
    LineColor #0078D4
    LineThickness 3.0
    FontColor #FFFFFF
}
:depth(2) {
    BackgroundColor #ffb900
    LineColor #ffb900
    LineThickness 3.0
    FontColor #000000
}
boxless {
    FontColor #000000
}
</style>
* Auto-Termination\n& Autoscaling
** Auto-Termination
***_ Shuts down idle clusters
***_ 30-60 mins for dev
***_ Set during create or edit
***_ Idle = all commands finished
***_ DStreams NOT monitored
** Autoscaling
***_ Dynamic worker count
***_ Min / max node settings
***_ Adds workers when busy
***_ Removes workers when idle
***_ 20-40% cost savings
** Configuration
***_ Enable during cluster create
***_ Edit existing cluster
***_ Specify inactivity minutes
@endmindmap
