@startmindmap
<style>
:depth(0) {
    BackgroundColor #FF5F46
    LineColor #FF5F46
    FontColor #ffffff
    LineThickness 3.0
}
:depth(1) {
    BackgroundColor #0078D4
    LineColor #0078D4
    LineThickness 3.0
    FontColor #FFFFFF
}
:depth(2) {
    BackgroundColor #ffb900
    LineColor #ffb900
    LineThickness 3.0
    FontColor #000000
}
boxless {
    FontColor #000000
}
</style>
* Create Alerts\nfor Monitoring
** Create Alert Steps
***_ Run query in Log Analytics
***_ New alert rule
***_ Configure Condition
***_ Define Action group
** Alert Scenarios
***_ Job failures > threshold
***_ Unusual access patterns
***_ Cluster creation spikes
** Job Failure Alert
***_ FailureCount > 5 per hour
***_ DatabricksJobs table
***_ Response contains "error/failed"
** Security Alert
***_ Access outside business hours
***_ hourofday < 6 or > 20
***_ Unity Catalog access
** Action Groups
***_ Email notifications
***_ SMS messages
***_ Azure mobile app
***_ ITSM integration
@endmindmap
