@startmindmap
<style>
:depth(0) {
    BackgroundColor #FF5F46
    LineColor #FF5F46
    FontColor #ffffff
    LineThickness 3.0
}
:depth(1) {
    BackgroundColor #0078D4
    LineColor #0078D4
    LineThickness 3.0
    FontColor #FFFFFF
}
:depth(2) {
    BackgroundColor #ffb900
    LineColor #ffb900
    LineThickness 3.0
    FontColor #000000
}
boxless {
    FontColor #000000
}
</style>
* Tags &\nPermissions
** Tags
***_ Labels or key-value pairs
***_ Categorize & filter jobs
***_ Group by team/project/env
***_ Propagate to clusters
***_ Enable cost attribution
** Permissions
*** CAN VIEW
****_ View config & run history
*** CAN RUN
****_ Trigger runs manually
*** CAN MANAGE RUN
****_ Cancel & restart runs
*** CAN MANAGE
****_ Edit config & permissions
** Best Practice
***_ Pipeline team: CAN MANAGE
***_ Operators: CAN RUN
***_ Stakeholders: CAN VIEW
@endmindmap
