@startmindmap
<style>
:depth(0) {
    BackgroundColor #FF5F46
    LineColor #FF5F46
    FontColor #ffffff
    LineThickness 3.0
}
:depth(1) {
    BackgroundColor #0078D4
    LineColor #0078D4
    LineThickness 3.0
    FontColor #FFFFFF
}
:depth(2) {
    BackgroundColor #ffb900
    LineColor #ffb900
    LineThickness 3.0
    FontColor #000000
}
boxless {
    FontColor #000000
}
</style>
* Compute\nResources
** Serverless
***_ Default option
***_ Azure manages infra
***_ Auto-scaling
***_ Low overhead
** Classic Jobs Compute
***_ Full cluster control
***_ Spark version & instance types
***_ Autoscaling policies
***_ Custom libraries
** SQL Warehouse
***_ For SQL tasks only
***_ Serverless or Pro
** Sharing Compute
***_ Reduces startup time
***_ Cost during idle periods
***_ Group related tasks
@endmindmap
