@startmindmap
<style>
:depth(0) {
    BackgroundColor #FF5F46
    LineColor #FF5F46
    FontColor #ffffff
    LineThickness 3.0
}
:depth(1) {
    BackgroundColor #0078D4
    LineColor #0078D4
    LineThickness 3.0
    FontColor #FFFFFF
}
:depth(2) {
    BackgroundColor #ffb900
    LineColor #ffb900
    LineThickness 3.0
    FontColor #000000
}
boxless {
    FontColor #000000
}
</style>
* Lakeflow Job\nStructure
** DAG
***_ Tasks as nodes
***_ Defines execution order
***_ Supports parallel tasks
** Required Components
***_ At least one task
***_ Compute resource
***_ Unique job name
** Task Types
***_ Notebook
***_ Python script
***_ SQL query
***_ Lakeflow Pipeline
@endmindmap
